### ISSUE TITLE
AI component

### ISSUE THREAD

**Issue by floatGOAT** [mcrozz/TelegaXO#11]
Считаю, что нужно зарезервировать User.username == "bot" для ботов. Это нормально?

**Comment by mcrozz** [comment]
Думаю нормально, ведь после username используется только в Telegram (на данный момент). Главное чтобы ты не вызвал метод send

**Comment by floatGOAT** [comment]
Также для ботов зарезервировал User.id == -1.
Однако встаёт вопрос: достаточно ли будет одного и того же id для всех ботов? Или же если в нескольких комнатах люди играют с ботами, то этим ботам нужны разные id?

**Comment by mcrozz** [comment]
А почему бы не использовать поле id? Выбери отрицательное число и готово.

**Comment by mcrozz** [comment]
Про полиморфизм ботов - будет достаточно

**Comment by floatGOAT** [comment]
@mcrozz Там некоторый прикол с имплементацией метода SendMessage - чтобы отправить сообщение, нужно указать user'а, который отправляет, и для его инициализации, я считаю, будет удобно использовать User.username == "bot"

**Comment by mcrozz** [comment]
Можно, только пока я вижу это как значение, которое нигде не будет использоваться

**Comment by floatGOAT** [comment]
Давай пока так оставлю, а потом посмотрим по степени нужности этой штуки?

**Comment by mcrozz** [comment]
Хорошо, как минимум не навредит
