### ISSUE TITLE
Room component

### ISSUE THREAD

**Issue by mcrozz** [mcrozz/TelegaXO#3]
# About
This class contains main game logic. This class should contain public method UpdateState, which will be called from outside with signature arguments as [Int32 ID, Int8 X, Int8 Y].

# Think ahead
Even if this game is turn based, you should check if you got response from player whom turn is it. To inform/warn player you can use method SendMessage(String message) on instance of player which should receive message.

**Comment by floatGOAT** [comment]
Игорь, привет! Это Андрей.
                    Короче, смотри, какой вариант будет идеальным:
        
                    1) Создаёшь
                    enum Fill { empty, tic, tac}
                    (она вроде у тебя уже есть, но в GitHub стёрлось, поэтому сейчас не могу точно восстановить)
                    
                    2) Когда создаёшь комнату, каждому игроку присваиваешь поле Room.Fill Marker - знак, который игрок будет ставить на поле (крестик или нолик).
                    Возможно, тебе покажется это избыточным, но мне было бы с такой информацией этим гораздо легче оперировать.
                    Получается что-то вроде: 
                    player1 = new Player(<какой-то DTO.Telegram.User>, Fill.tac);
                    player2 = new Player(<какой-то DTO.Telegram.User>, Fill.tic);

                    3) У ботов id = -1, и в конструкторе они принимают только Room.Fill Marker

**Comment by mcrozz** [comment]
Третий пункт не совпадает с твоим текущим @floatGOAT. Игорю не нужно ничего создавать, нужно только присвоить tic или tac.

**Comment by mcrozz** [comment]
Бот или игрок будет решаться отдельно от Room в Game
